name: orville-postgresql-libpq
version: '0.9.0.0'
synopsis: ORM
description: ORM library for PostgreSQL
category: Database
author: Flipstone Technology Partners
maintainer: development@flipstone.com
license: MIT
git: git@github.com:flipstone/orville.git
tested-with: GHC == 8.6.5
extra-source-files:
  - README.md

library:
  source-dirs: src
  exposed-modules:
    - Database.Orville.PostgreSQL
    - Database.Orville.PostgreSQL.Connection
    - Database.Orville.PostgreSQL.Internal.ExecutionResult
    - Database.Orville.PostgreSQL.Internal.Expr
    - Database.Orville.PostgreSQL.Internal.SqlType
  ghc-options:
    - -Wall
    - -fwarn-incomplete-uni-patterns
    - -fwarn-incomplete-record-updates
  dependencies:
    - base >=4.8 && <5
    - attoparsec
    - bytestring
    - postgresql-libpq >= 0.9.4.2 && <0.10
    - resource-pool
    - text
    - time >=1.5


tests:
  spec:
    source-dirs: test
    main: Main.hs
    other-modules:
      - Test.SqlType
    dependencies:
      - base
      - bytestring
      - mtl
      - orville-postgresql-libpq
      - resource-pool
      - tasty
      - tasty-hspec
      - text
      - time
    ghc-options:
      - -j
      - -Wall
      - -Werror
      - -Wcompat
      - -Widentities
      - -Wincomplete-uni-patterns
      - -Wincomplete-record-updates
      - -Wmissing-local-signatures
      - -Wmissing-export-lists
      - -Wno-implicit-prelude
      - -Wno-safe
      - -Wno-unsafe
      - -Wnoncanonical-monad-instances
      - -Wredundant-constraints
      - -Wpartial-fields
      - -Wmissed-specialisations
