version: "3"
services:
  dev:
    build: .
    volumes:
      - .:/orville
      - stack-work:/orville/.stack-work
      - stack-root:/stack-root
    working_dir: /orville
    depends_on:
      - oracle
    environment:
      TEST_CONN_STRING: "DRIVER={Oracle 12c ODBC driver};DBQ=oracle:1521/ORCLPDB1.localdomain;UID=orville;PWD=test;"
      LD_LIBRARY_PATH: /opt/oracle/instantclient_12_1:$LD_LIBRARY_PATH
      TNS_ADMIN: /orville/tnsnames.ora
    command: sh
      # ./test-loop stack-lts-13.12.yml
    # A TTY is required for the test-loop script to use
    # stack test. stdin_open would be sufficient, but
    # allocating a tty provides colorful test output :)
    tty: true

  oracle:
    image: store/oracle/database-enterprise:12.2.0.1
    ports:
      - 1521:1521

volumes:
  stack-root:
  stack-work:
